# main text of home
name: Samvid Dharanikota
bio: Grad Student at Carnegie Mellon University

# twitter summary info
# description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-local: true
resume-url: assets/SamvidDharanikota.pdf

url: https://samvid.me

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: mydisqus # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: samvid25
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: samvid-dharanikota
# youtube: myyoutube
# spotify: myspotify
github: samvid25
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: samvid.dharani@gmail.com
gscholar: https://scholar.google.co.in/citations?user=CC9r754AAAAJ

authors:
    samvid:
        name: Samvid Dharanikota
        bio: Grad Student at Carnegie Mellon University
        external-image: false
        picture: assets/images/profile.jpg
        # twitter: johndoe
    # jamesfoster:
    #     name: James Foster
    #     bio: A Man who develops software with coffee
    #     external-image: false
    #     picture: assets/images/james.jpg
    #     twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# Pages to be displayed
projects: true
about: false
blog: false
papers: true
experience: true

## Blog
read-time: true             # do you want to show the "read time" of the posts?
show-tags: false             # do you want to show the "tags" inside the posts?
related: true               # related posts inside a post?
post-advance-links: [blog]  # Display links for next and previous posts for the specified categories
show-author: true           # show author block at the end of a post ?

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md"]
